# Generated by Django 4.1.6 on 2023-06-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_director', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='death_date',
        ),
    ]
