# Generated by Django 4.1.6 on 2023-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_director', '0003_rename_summary_film_storyline_director_awards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='stars',
            new_name='main_actors',
        ),
        migrations.AddField(
            model_name='director',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.URLField(default='movies_project/static/images/no_image.png'),
        ),
    ]
