# Generated by Django 4.1.6 on 2023-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_director', '0005_alter_film_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.CharField(default='Edad', max_length=4),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/340/230'),
        ),
        migrations.AlterField(
            model_name='film',
            name='creation_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/340/230'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_actors',
            field=models.CharField(max_length=100),
        ),
    ]
