# Generated by Django 4.1.6 on 2023-06-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_director', '0006_alter_director_age_alter_director_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(default='0h', max_length=10),
        ),
    ]
